#!/usr/bin/env node
/* Builds the vendored CodeMirror bundle AND its license notices.
 * MIT requires the copyright + permission notice to accompany all copies,
 * so this collects the LICENSE of every package that actually lands in
 * the bundle (discovered via esbuild's metafile — no hand-maintained
 * list to rot) into docs/vendor/LICENSES.txt, and stamps the bundle
 * with a pointer banner. The build FAILS if any bundled package has no
 * license file. */

import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";

const result = await build({
  entryPoints: ["tools/editor_bundle_entry.js"],
  bundle: true,
  format: "esm",
  minify: true,
  metafile: true,
  outfile: "docs/vendor/codemirror.js",
  banner: {
    js: "/*! Bundled CodeMirror 6 and dependencies — MIT licensed.\n" +
        " * Full copyright and permission notices: ./LICENSES.txt\n" +
        " * (same directory). Regenerate: npm run build:editor */",
  },
  logLevel: "info",
});

const pkgs = new Set();
for (const f of Object.keys(result.metafile.inputs)) {
  const m = f.match(/node_modules\/((@[^/]+\/)?[^/]+)/);
  if (m) pkgs.add(m[1]);
}

let notices = "Third-party license notices for docs/vendor/codemirror.js\n" +
  "(regenerated by tools/build_editor.mjs; covers every bundled package)\n";
const missing = [];
for (const p of [...pkgs].sort()) {
  let text = null;
  for (const name of ["LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE"]) {
    try { text = readFileSync(`node_modules/${p}/${name}`, "utf8"); break; }
    catch { /* try next */ }
  }
  if (text === null) { missing.push(p); continue; }
  const meta = JSON.parse(readFileSync(`node_modules/${p}/package.json`, "utf8"));
  notices += `\n${"=".repeat(72)}\n${p}@${meta.version} (${meta.license})\n${"=".repeat(72)}\n${text}`;
}
if (missing.length) {
  console.error("bundled packages without a license file:", missing.join(", "));
  process.exit(1);
}
writeFileSync("docs/vendor/LICENSES.txt", notices);
console.log(`LICENSES.txt: ${pkgs.size} packages covered`);
